name: nyxx_interactions_template
description: Ready to go template for nyxx_interactions
version: 0.1.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  args: ^2.3.0
  nyxx: ^3.2.7
  nyxx_interactions: ^3.3.0
  path: ^1.8.1
  yaml: ^3.1.0

scripts:
  run:dev: dart run bin/nyxx_interactions_template.dart --dart-env=dev
  run:dev_aot: cd prod && nyxx_interactions_template.exe --dart-env=dev
  run:prod: cd prod && nyxx_interactions_template.exe --dart-env=prod
  build:aot: dart compile exe bin/nyxx_interactions_template.dart -o prod/nyxx_interactions_template.exe